import {
  pgTable,
  uuid,
  integer,
  text,
  timestamp,
  date,
  unique,
  uniqueIndex,
  index,
  foreignKey,
} from "drizzle-orm/pg-core";
import { billingCycleItemStatusEnum, settlementMethodEnum, pointTxnTypeEnum } from "./enums";
import { operators } from "./operators";
import { customers } from "./customers";
import { deliveryLedger } from "./delivery";

// Generated by the scheduled billing-day Inngest job. Immutable after
// generation: previous_balance_cents, new_charges_cents, and
// total_due_cents on billing_cycle_items are frozen the moment a cycle is
// created (enforced by a trigger — see drizzle/000X_billing_cycle_immutability.sql).
// Anything that happens after freeze — a late skip, a dispute credit granted
// after the cycle closed — is a new adjustment/ledger line that flows into
// the *next* cycle's new_charges_cents. A frozen cycle is never mutated to
// reflect it.
export const billingCycles = pgTable("billing_cycles", {
  id: uuid("id").primaryKey().defaultRandom(),
  operatorId: uuid("operator_id").notNull().references(() => operators.id, { onDelete: "cascade" }),
  cycleDate: date("cycle_date").notNull(),
  periodStart: date("period_start").notNull(),
  periodEnd: date("period_end").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  uniqCycle: uniqueIndex("billing_cycles_operator_date_uniq").on(t.operatorId, t.cycleDate),
  // Referenced by composite FK from billing_cycle_items.
  uniqSelf: unique("billing_cycles_id_operator_uniq").on(t.id, t.operatorId),
}));

export const billingCycleItems = pgTable("billing_cycle_items", {
  id: uuid("id").primaryKey().defaultRandom(),
  operatorId: uuid("operator_id").notNull().references(() => operators.id, { onDelete: "cascade" }),
  billingCycleId: uuid("billing_cycle_id").notNull(),
  customerId: uuid("customer_id").notNull(),
  previousBalanceCents: integer("previous_balance_cents").notNull().default(0),
  newChargesCents: integer("new_charges_cents").notNull(),
  totalDueCents: integer("total_due_cents").notNull(),
  amountPaidCents: integer("amount_paid_cents").notNull().default(0),
  status: billingCycleItemStatusEnum("status").notNull().default("unpaid"),
  graceEndsAt: timestamp("grace_ends_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  uniqItem: uniqueIndex("billing_cycle_items_cycle_customer_uniq").on(t.billingCycleId, t.customerId),
  billingCycleFk: foreignKey({
    columns: [t.billingCycleId, t.operatorId],
    foreignColumns: [billingCycles.id, billingCycles.operatorId],
    name: "billing_cycle_items_cycle_operator_fk",
  }),
  customerFk: foreignKey({
    columns: [t.customerId, t.operatorId],
    foreignColumns: [customers.id, customers.operatorId],
    name: "billing_cycle_items_customer_operator_fk",
  }),
  customerIdx: index("billing_cycle_items_customer_idx").on(t.customerId),
  // Referenced by composite FK from settlements.billing_cycle_item_id.
  uniqSelf: unique("billing_cycle_items_id_operator_uniq").on(t.id, t.operatorId),
}));

export const settlements = pgTable("settlements", {
  id: uuid("id").primaryKey().defaultRandom(),
  operatorId: uuid("operator_id").notNull().references(() => operators.id, { onDelete: "cascade" }),
  customerId: uuid("customer_id").notNull(),
  billingCycleItemId: uuid("billing_cycle_item_id"), // null for prepaid renewals
  amountCents: integer("amount_cents").notNull(),
  method: settlementMethodEnum("method").notNull().default("e_transfer"),
  paidAt: timestamp("paid_at", { withTimezone: true }).notNull(),
  note: text("note"),
  idempotencyKey: text("idempotency_key").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  uniqIdem: uniqueIndex("settlements_idempotency_uniq").on(t.idempotencyKey),
  customerFk: foreignKey({
    columns: [t.customerId, t.operatorId],
    foreignColumns: [customers.id, customers.operatorId],
    name: "settlements_customer_operator_fk",
  }),
  billingCycleItemFk: foreignKey({
    columns: [t.billingCycleItemId, t.operatorId],
    foreignColumns: [billingCycleItems.id, billingCycleItems.operatorId],
    name: "settlements_cycle_item_operator_fk",
  }),
  customerIdx: index("settlements_customer_idx").on(t.customerId),
  // Referenced by composite FK from point_transactions.related_settlement_id.
  uniqSelf: unique("settlements_id_operator_uniq").on(t.id, t.operatorId),
}));

// Immutable ledger; customers.points_balance is a cache updated in the same
// transaction as the insert here, guarded by the idempotency key so a
// retried renewal or a double-tapped manual adjustment can never double-apply.
export const pointTransactions = pgTable("point_transactions", {
  id: uuid("id").primaryKey().defaultRandom(),
  operatorId: uuid("operator_id").notNull().references(() => operators.id, { onDelete: "cascade" }),
  customerId: uuid("customer_id").notNull(),
  type: pointTxnTypeEnum("type").notNull(),
  points: integer("points").notNull(), // signed
  relatedSettlementId: uuid("related_settlement_id"),
  relatedDeliveryLedgerId: uuid("related_delivery_ledger_id"),
  note: text("note"), // required for manual_adjust
  idempotencyKey: text("idempotency_key").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  uniqIdem: uniqueIndex("point_transactions_idempotency_uniq").on(t.idempotencyKey),
  customerFk: foreignKey({
    columns: [t.customerId, t.operatorId],
    foreignColumns: [customers.id, customers.operatorId],
    name: "point_transactions_customer_operator_fk",
  }),
  settlementFk: foreignKey({
    columns: [t.relatedSettlementId, t.operatorId],
    foreignColumns: [settlements.id, settlements.operatorId],
    name: "point_transactions_settlement_operator_fk",
  }),
  deliveryLedgerFk: foreignKey({
    columns: [t.relatedDeliveryLedgerId, t.operatorId],
    foreignColumns: [deliveryLedger.id, deliveryLedger.operatorId],
    name: "point_transactions_ledger_operator_fk",
  }),
  customerIdx: index("point_transactions_customer_idx").on(t.customerId),
}));
